# Overview
I think the `load_config` function in astera is a good sample function for Dylan...there are a few variables,
and some with nested structures (which is the key test case to make sure we have "dependencies" defined first)

In [1]:
!ls ~/exp_builds/astera.exp/rundata/run1/0.fighter
# !ls ~/exp_builds/astera.exp

0.fighter	   function_params.csv	      locals.stats.csv
0.fighter.debug    function_params.stats.csv  _raw_debug_locals.csv
ast_dumps	   functions.csv	      _raw_dwarf_locals.csv
fighter		   ghidra_ast.debug.json      _raw_stripped_locals.csv
fighter.debug	   ghidra_ast.json
fighter.dwarf.sdb  locals.csv

In [2]:
from pathlib import Path
import pandas as pd

bin_folder = Path.home()/'exp_builds/astera.exp/rundata/run1/0.fighter'

funcs_df = pd.read_csv(bin_folder/'functions.csv')
locals_df = pd.read_csv(bin_folder/'locals.csv')

raw_debug = pd.read_csv(bin_folder/'_raw_debug_locals.csv')
raw_dwarf = pd.read_csv(bin_folder/'_raw_dwarf_locals.csv')
raw_strip = pd.read_csv(bin_folder/'_raw_stripped_locals.csv')

In [3]:
addr = funcs_df[funcs_df.FunctionName_Debug=='init_game'].FunctionStart.iloc[0]
# pd.set_option('display.expand_frame_repr', False)
# pd.options.display.max_columns = 10
with pd.option_context('display.max_rows', None, 'display.max_columns', None,'display.max_colwidth', 20):
    print(len(locals_df[locals_df.FunctionStart==addr]))

46

In [4]:
raw_debug[raw_debug.FunctionStart==addr]

,FunctionStart,Name,Signature,Type,LocType,LocRegName,LocOffset,TypeCategory,TypeSeq
411,1351728,lVar1,"15,1739",int64,unique,NaN,49792,BUILTIN,int64
412,1351728,afVar2,"144,144,494",float[2],unique,NaN,268435571,ARR,"ARR,float"
413,1351728,lVar3,"400,408,408,408",int64,register,rcx,8,BUILTIN,int64
414,1351728,ppVar4,"405,408,408,408",player_t*,register,rdi,56,PTR,"PTR,STRUCT"
415,1351728,in_FS_OFFSET,"15,1739",int64,register,fs_offset,272,BUILTIN,int64
416,1351728,bVar5,"4,408",uchar,register,df,522,BUILTIN,uchar
417,1351728,extraout_XMM0_Qa,494,float[2],register,xmm0_qa,4608,ARR,"ARR,float"
418,1351728,extraout_XMM0_Qa_00,494,float[2],register,xmm0_qa,4608,ARR,"ARR,float"
419,1351728,in_XMM1_Da,144,uint32,register,xmm1_da,4640,BUILTIN,uint32
420,1351728,fVar6,"271,281",float,register,xmm1_da,4640,BUILTIN,float
421,1351728,in_XMM1_Db,144,uint32,register,xmm1_db,4644,BUILTIN,uint32
422,1351728,uVar7,"191,281",uint32,register,xmm1_db,4644,BUILTIN,uint32
423,1351728,local_378,"505,548,548,555,555,576,576,583,583,865,908,90...",uchar[32],stack,NaN,-888,ARR,"ARR,uchar"
424,1351728,local_358,"604,964,1324",r_sheet*,stack,NaN,-856,PTR,"PTR,STRUCT"
425,1351728,local_350,"611,971,1331",uint64,stack,NaN,-848,BUILTIN,uint64
426,1351728,local_348,"632,992,1352",uint64,stack,NaN,-840,BUILTIN,uint64
427,1351728,local_340,"639,999,1359",uint64,stack,NaN,-832,BUILTIN,uint64
428,1351728,local_338,"660,1020,1380",uint64,stack,NaN,-824,BUILTIN,uint64
429,1351728,local_330,"667,1027,1387",uint64,stack,NaN,-816,BUILTIN,uint64
430,1351728,local_328,"688,688,1048,1048,1408,1408",uint64,stack,NaN,-808,BUILTIN,uint64
431,1351728,local_320,"695,695,1055,1055,1415,1415",uint64,stack,NaN,-800,BUILTIN,uint64
432,1351728,local_318,"828,1188,1548",uint64,stack,NaN,-792,BUILTIN,uint64
433,1351728,local_310,"723,723,1083,1083,1443,1443",uint64,stack,NaN,-784,BUILTIN,uint64
434,1351728,local_308,"744,744,1104,1104,1464,1464",uint64,stack,NaN,-776,BUILTIN,uint64
435,1351728,local_300,"751,751,1111,1111,1471,1471",uint64,stack,NaN,-768,BUILTIN,uint64
436,1351728,local_2f8,"772,772,1132,1132,1492,1492",uint64,stack,NaN,-760,BUILTIN,uint64
437,1351728,local_2f0,"779,779,1139,1139,1499,1499",uint64,stack,NaN,-752,BUILTIN,uint64
438,1351728,local_2e8,"800,800,1160,1160,1520,1520",uint64,stack,NaN,-744,BUILTIN,uint64
439,1351728,local_2e0,"807,807,1167,1167,1527,1527",uint64,stack,NaN,-736,BUILTIN,uint64
440,1351728,local_2d8,"821,821,1181,1181,1541,1541",uint64,stack,NaN,-728,BUILTIN,uint64
441,1351728,width,30,int32,stack,NaN,-704,BUILTIN,int32
442,1351728,height,40,int32,stack,NaN,-700,BUILTIN,int32
443,1351728,sword_swoosh,"1572,1601",r_anim*,stack,NaN,-696,PTR,"PTR,STRUCT"
444,1351728,player_pos,"58,74,121,179,207,271,477,519,879,1239",float[2],stack,NaN,-688,ARR,"ARR,float"
445,1351728,player_halfsize,"90,106,114",float[2],stack,NaN,-680,ARR,"ARR,float"
446,1351728,sword_pos,"179,207,258",float[2],stack,NaN,-672,ARR,"ARR,float"
447,1351728,sword_halfsize,"227,243,251",float[2],stack,NaN,-664,ARR,"ARR,float"
448,1351728,zero,NaN,float[2],stack,NaN,-656,ARR,"ARR,float"
449,1351728,halfsize,NaN,float[2],stack,NaN,-648,ARR,"ARR,float"
450,1351728,sprite_size,"364,380,512,872,1232",float[2],stack,NaN,-640,ARR,"ARR,float"
451,1351728,player_col,NaN,c_aabb,stack,NaN,-632,STRUCT,STRUCT
452,1351728,sword_col,NaN,c_aabb,stack,NaN,-616,STRUCT,STRUCT

In [5]:
raw_strip[raw_strip.FunctionStart==addr]

,FunctionStart,Name,Signature,Type,LocType,LocRegName,LocOffset,TypeCategory,TypeSeq
391,1351728,lVar1,"400,408,408,408",int64,register,rcx,8,BUILTIN,int64
392,1351728,puVar2,"405,408,408,408",uint64*,register,rdi,56,PTR,"PTR,uint64"
393,1351728,in_FS_OFFSET,"15,1739",int64,register,fs_offset,272,BUILTIN,int64
394,1351728,bVar3,"4,408",uchar,register,df,522,BUILTIN,uchar
395,1351728,fVar4,"271,281",float,register,xmm1_da,4640,BUILTIN,float
396,1351728,uVar5,"0,144",uint32,register,xmm1_db,4644,BUILTIN,uint32
397,1351728,uVar6,"0,144,191,281",uint32,register,xmm1_db,4644,BUILTIN,uint32
398,1351728,local_378,"505,548,865,908,1225,1268",uint64,stack,NaN,-888,BUILTIN,uint64
399,1351728,local_370,"555,915,1275",uint64,stack,NaN,-880,BUILTIN,uint64
400,1351728,local_368,"576,936,1296",uint64,stack,NaN,-872,BUILTIN,uint64
401,1351728,local_360,"583,943,1303",uint64,stack,NaN,-864,BUILTIN,uint64
402,1351728,local_358,"604,964,1324",uint64,stack,NaN,-856,BUILTIN,uint64
403,1351728,local_350,"611,971,1331",uint64,stack,NaN,-848,BUILTIN,uint64
404,1351728,local_348,"632,992,1352",uint64,stack,NaN,-840,BUILTIN,uint64
405,1351728,local_340,"639,999,1359",uint64,stack,NaN,-832,BUILTIN,uint64
406,1351728,local_338,"660,1020,1380",uint64,stack,NaN,-824,BUILTIN,uint64
407,1351728,local_330,"667,1027,1387",uint64,stack,NaN,-816,BUILTIN,uint64
408,1351728,local_328,"688,1048,1408",uint64,stack,NaN,-808,BUILTIN,uint64
409,1351728,local_320,"695,1055,1415",uint64,stack,NaN,-800,BUILTIN,uint64
410,1351728,local_318,"828,1188,1548",uint64,stack,NaN,-792,BUILTIN,uint64
411,1351728,local_310,"723,1083,1443",uint64,stack,NaN,-784,BUILTIN,uint64
412,1351728,local_308,"744,1104,1464",uint64,stack,NaN,-776,BUILTIN,uint64
413,1351728,local_300,"751,1111,1471",uint64,stack,NaN,-768,BUILTIN,uint64
414,1351728,local_2f8,"772,1132,1492",uint64,stack,NaN,-760,BUILTIN,uint64
415,1351728,local_2f0,"779,1139,1499",uint64,stack,NaN,-752,BUILTIN,uint64
416,1351728,local_2e8,"800,1160,1520",uint64,stack,NaN,-744,BUILTIN,uint64
417,1351728,local_2e0,"807,1167,1527",uint64,stack,NaN,-736,BUILTIN,uint64
418,1351728,local_2d8,"821,1181,1541",uint64,stack,NaN,-728,BUILTIN,uint64
419,1351728,local_2c0,30,uint32,stack,NaN,-704,BUILTIN,uint32
420,1351728,local_2bc,40,uint32,stack,NaN,-700,BUILTIN,uint32
421,1351728,local_2b8,"1572,1601",uint64,stack,NaN,-696,BUILTIN,uint64
422,1351728,local_2b0,"58,121,179,477,519,879,1239",float,stack,NaN,-688,BUILTIN,float
423,1351728,local_2ac,"74,207,271",float,stack,NaN,-684,BUILTIN,float
424,1351728,local_2a8,"90,114",uint32,stack,NaN,-680,BUILTIN,uint32
425,1351728,local_2a4,106,uint32,stack,NaN,-676,BUILTIN,uint32
426,1351728,local_2a0,"179,258",float,stack,NaN,-672,BUILTIN,float
427,1351728,local_29c,207,float,stack,NaN,-668,BUILTIN,float
428,1351728,local_298,"227,251",uint32,stack,NaN,-664,BUILTIN,uint32
429,1351728,local_294,243,uint32,stack,NaN,-660,BUILTIN,uint32
430,1351728,local_290,304,uint32,stack,NaN,-656,BUILTIN,uint32
431,1351728,local_28c,316,uint32,stack,NaN,-652,BUILTIN,uint32
432,1351728,local_288,332,uint32,stack,NaN,-648,BUILTIN,uint32
433,1351728,local_284,348,uint32,stack,NaN,-644,BUILTIN,uint32
434,1351728,local_280,"364,512,872,1232",uint32,stack,NaN,-640,BUILTIN,uint32
435,1351728,local_27c,380,uint32,stack,NaN,-636,BUILTIN,uint32
436,1351728,local_278,"134,425",uint64,stack,NaN,-632,BUILTIN,uint64
437,1351728,local_270,"144,432",uint64,stack,NaN,-624,BUILTIN,uint64
438,1351728,local_268,494,uint64,stack,NaN,-616,BUILTIN,uint64
439,1351728,local_260,494,uint64,stack,NaN,-608,BUILTIN,uint64
440,1351728,local_10,"15,1739",int64,stack,NaN,-16,BUILTIN,int64

In [6]:
raw_dwarf[raw_dwarf.FunctionStart==addr]

,Name,Type,LocType,LocRegName,LocOffset,FunctionStart,FunctionName,TypeCategory,TypeSeq
104,width,int32,UndefinedLoc,NaN,NaN,1351728,init_game,BUILTIN,int32
105,height,int32,UndefinedLoc,NaN,NaN,1351728,init_game,BUILTIN,int32
106,player_pos,float[2],UndefinedLoc,NaN,NaN,1351728,init_game,ARR,"ARR,float"
107,player_halfsize,float[2],UndefinedLoc,NaN,NaN,1351728,init_game,ARR,"ARR,float"
108,player_col,c_aabb,UndefinedLoc,NaN,NaN,1351728,init_game,STRUCT,STRUCT
109,sword_pos,float[2],UndefinedLoc,NaN,NaN,1351728,init_game,ARR,"ARR,float"
110,sword_halfsize,float[2],UndefinedLoc,NaN,NaN,1351728,init_game,ARR,"ARR,float"
111,sword_col,c_aabb,UndefinedLoc,NaN,NaN,1351728,init_game,STRUCT,STRUCT
112,zero,float[2],UndefinedLoc,NaN,NaN,1351728,init_game,ARR,"ARR,float"
113,halfsize,float[2],UndefinedLoc,NaN,NaN,1351728,init_game,ARR,"ARR,float"
114,sprite_size,float[2],UndefinedLoc,NaN,NaN,1351728,init_game,ARR,"ARR,float"
115,sword_swoosh,r_anim*,UndefinedLoc,NaN,NaN,1351728,init_game,PTR,"PTR,STRUCT"

# Export DataTypeArchive
Ok, try this REALLY QUICK!
1. **I need this to be able to try out/investigate the member offset dataset!!**
2. If I can hand Dylan the `sword_swoosh` local from `init_game` that is a great test case

In [7]:
import pyhidra
pyhidra.start()

In [8]:
!ls ~/ghidra_projects

aarch64test.gpr  astera3.gpr  astera.gpr   astera.lock~
aarch64test.rep  astera3.rep  astera.lock  astera.rep

In [9]:
import typing
if typing.TYPE_CHECKING:
    import ghidra
    from ghidra.ghidra_builtins import *

from ghidralib.datatypes import to_varlib_dtype

# to_varlib_dtype()
import ghidra
from ghidra.base.project import GhidraProject

gproj = GhidraProject.openProject(Path.home()/'ghidra_projects', 'astera', False)

In [10]:
list(list(gproj.getRootFolder().getFolders())[0].getFiles())
prog = gproj.openProgram('/run1.gcc-O0.astera', '0.fighter.debug', True)

In [11]:
dtmgr = prog.getDataTypeManager()
s = dtmgr.getAllStructures().next()

In [12]:
stype = to_varlib_dtype(s, s.getLength())
stype.sid

# len([to_varlib_dtype(s, s.getLength()) for s in dtmgr.getAllStructures()])
[to_varlib_dtype(s, s.getLength()).name for s in dtmgr.getAllStructures()][:10]

['Elf64_Ehdr',
 'Elf64_Phdr',
 'Elf64_Shdr',
 'Elf64_Dyn',
 'Elf64_Sym',
 'Elf64_Rela',
 'NoteAbiTag',
 'NoteGnuProperty_4',
 'NoteGnuPropertyElement_4',
 '_IO_FILE']

In [13]:
from varlib.datatype import StructField

comp = list(s.getComponents())[0]
comp.getDataType()
comp.getOffset()
comp.getFieldName()
comp.getComment()
comp.getDefaultFieldName()
comp.getKey()
comp.getLength()
comp.getDataType().getLength()
comp.getOrdinal()
comp.getParent()
comp.getEndOffset()

f = StructField(to_varlib_dtype(comp.getDataType(), comp.getLength()), comp.getFieldName())
f.name
print(f)
print(f.name)
type(comp)

uchar e_ident_magic_num
e_ident_magic_num

# Export Ghidra Data Type Archive
The code below needs to be moved to `ghidralib`

In [14]:
from ghidralib.export_types import export_ghidra_types_to_sdb

sdb = export_ghidra_types_to_sdb(dtmgr)
sdb.to_json('astera.debug.sdb')

100%|██████████| 406/406 [00:00<00:00, 1931.71it/s]

In [15]:
k = list(sdb.structs_by_id.keys())[35]
print(sdb.structs_by_id[k])

struct r_anim_viewer {
	0x0: r_anim* anim
	0x8: double time
	0x10: double rate
	0x18: uint32 curr
	0x1c: uint32 count
	0x20: uchar state
	0x21: uchar pstate
	0x22: char loop
}

In [16]:
!ls -Ahl

total 2.6M
-rw-rw-r-- 1 cls0027 cls0027 1.2M Feb  3 11:59 astera.debug.sdb
-rw-rw-r-- 1 cls0027 cls0027 1.1M Feb  1 19:00 astera.sdb
-rw-rw-r-- 1 cls0027 cls0027 3.9K Feb  1 10:47 ast_updates.ipynb
-rw-rw-r-- 1 cls0027 cls0027 281K Feb  3 11:35 dylan_sandbox.ipynb
drwxrwxr-x 8 cls0027 cls0027 4.0K Feb  2 20:42 .git
-rw-rw-r-- 1 cls0027 cls0027   34 Feb  1 19:11 .gitignore
-rw-rw-r-- 1 cls0027 cls0027   90 May 15  2023 pyproject.toml
-rw-rw-r-- 1 cls0027 cls0027   72 Aug 21 19:57 README.md
-rw-rw-r-- 1 cls0027 cls0027  524 Jan 30 20:39 setup.cfg
drwxrwxr-x 7 cls0027 cls0027 4.0K Jan 30 09:06 src

In [17]:
sdb2 = sdb.from_json('astera.debug.sdb')

In [18]:
sid = sdb2.sids_by_name['r_anim'][0]
sdb2.structs_by_id[sid]

struct r_anim {
	0x0: uint32 id
	0x8: uint32* frames
	0x10: double* lengths
	0x18: uint32 count
	0x20: double rate
	0x28: r_sheet* sheet
	0x30: char loop
}

In [19]:
sdb2.structs_by_id.keys()

dict_keys([72057594037927936, 72057594037927937, 72057594037927938, 72057594037927939, 72057594037927940, 72057594037927941, 72057594037927942, 72057594037927943, 72057594037927944, 72057594037927945, 72057594037927946, 72057594037927947, 72057594037927948, 72057594037927949, 72057594037927950, 72057594037927951, 72057594037927952, 72057594037927953, 72057594037927954, 72057594037927955, 72057594037927956, 72057594037927957, 72057594037927958, 72057594037927959, 72057594037927960, 72057594037927961, 72057594037927962, 72057594037927963, 72057594037927964, 72057594037927965, 72057594037927966, 72057594037927967, 72057594037927968, 72057594037927969, 72057594037927970, 72057594037927971, 72057594037927973, 72057594037927974, 72057594037927975, 72057594037927976, 72057594037927977, 72057594037927978, 72057594037927980, 72057594037927981, 72057594037927982, 72057594037927983, 72057594037927984, 72057594037927985, 72057594037927986, 72057594037927987, 72057594037927988, 72057594037927989, 72057594037927990, 72057594037927991, 72057594037927992, 72057594037927993, 72057594037927994, 72057594037927995, 72057594037927996, 72057594037927997, 72057594037927999, 72057594037928000, 72057594037928001, 72057594037928002, 72057594037928004, 72057594037928005, 72057594037928006, 72057594037928007, 72057594037928008, 72057594037928009, 72057594037928010, 72057594037928011, 72057594037928012, 72057594037928013, 72057594037928015, 72057594037928016, 72057594037928017, 72057594037928018, 72057594037928019, 72057594037928020, 72057594037928021, 72057594037928022, 72057594037928023, 72057594037928024, 72057594037928025, 72057594037928026, 72057594037928027, 72057594037928028, 72057594037928029, 72057594037928031, 72057594037928032, 72057594037928033, 72057594037928034, 72057594037928035, 72057594037928036, 72057594037928037, 72057594037928038, 72057594037928040, 72057594037928042, 72057594037928043, 72057594037928044, 72057594037928045, 72057594037928046, 72057594037928047, 72057594037928048, 72057594037928049, 72057594037928050, 72057594037928051, 72057594037928052, 72057594037928053, 72057594037928054, 72057594037928055, 72057594037928056, 72057594037928057, 72057594037928058, 72057594037928059, 72057594037928060, 72057594037928061, 72057594037928062, 72057594037928063, 72057594037928064, 72057594037928065, 72057594037928066, 72057594037928067, 72057594037928068, 72057594037928069, 72057594037928070, 72057594037928071, 72057594037928072, 72057594037928073, 72057594037928074, 72057594037928076, 72057594037928077, 72057594037928078, 72057594037928079, 72057594037928080, 72057594037928082, 72057594037928083, 72057594037928084, 72057594037928085, 72057594037928086, 72057594037928087, 72057594037928088, 72057594037928089, 72057594037928090, 72057594037928091, 72057594037928092, 72057594037928093, 72057594037928094, 72057594037928095, 72057594037928096, 72057594037928097, 72057594037928098, 72057594037928099, 72057594037928100, 72057594037928101, 72057594037928102, 72057594037928103, 72057594037928104, 72057594037928105, 72057594037928106, 72057594037928107, 72057594037928108, 72057594037928109, 72057594037928110, 72057594037928111, 72057594037928112, 72057594037928113, 72057594037928114, 72057594037928115, 72057594037928116, 72057594037928117, 72057594037928118, 72057594037928119, 72057594037928120, 72057594037928121, 72057594037928122, 72057594037928123, 72057594037928124, 72057594037928125, 72057594037928126, 72057594037928127, 72057594037928128, 72057594037928129, 72057594037928130, 72057594037928131, 72057594037928132, 72057594037928133, 72057594037928134, 72057594037928135, 72057594037928136, 72057594037928137, 72057594037928138, 72057594037928139, 72057594037928140, 72057594037928141, 72057594037928142, 72057594037928143, 72057594037928144, 72057594037928145, 72057594037928146, 72057594037928147, 72057594037928148, 72057594037928149, 72057594037928150, 72057594037928151, 72057594037928152, 72057594037928153, 72057594037928154, 72057594037928155, 72057594037928156, 72057594037928157, 72057594037928158, 72057594037928159, 72057594037928160, 72057594037928161, 72057594037928162, 72057594037928164, 72057594037928165, 72057594037928166, 72057594037928167, 72057594037928168, 72057594037928169, 72057594037928170, 72057594037928171, 72057594037928172, 72057594037928173, 72057594037928174, 72057594037928175, 72057594037928176, 72057594037928177, 72057594037928178, 72057594037928179, 72057594037928181, 72057594037928182, 72057594037928183, 72057594037928184, 72057594037928185, 72057594037928186, 72057594037928187, 72057594037928188, 72057594037928189, 72057594037928190, 72057594037928191, 72057594037928192, 72057594037928193, 72057594037928194, 72057594037928195, 72057594037928196, 72057594037928197, 72057594037928198, 72057594037928199, 72057594037928200, 72057594037928201, 72057594037928202, 72057594037928203, 72057594037928204, 72057594037928205, 72057594037928206, 72057594037928207, 72057594037928208, 72057594037928210, 72057594037928211, 72057594037928212, 72057594037928213, 72057594037928214, 72057594037928215, 72057594037928216, 72057594037928217, 72057594037928218, 72057594037928219, 72057594037928220, 72057594037928221, 72057594037928222, 72057594037928223, 72057594037928224, 72057594037928225, 72057594037928226, 72057594037928227, 72057594037928228, 72057594037928229, 72057594037928230, 72057594037928231, 72057594037928232, 72057594037928233, 72057594037928234, 72057594037928235, 72057594037928236, 72057594037928237, 72057594037928238, 72057594037928239, 72057594037928240, 72057594037928241, 72057594037928242, 72057594037928243, 72057594037928244, 72057594037928245, 72057594037928246, 72057594037928247, 72057594037928248, 72057594037928249, 72057594037928250, 72057594037928251, 72057594037928252, 72057594037928253, 72057594037928254, 72057594037928255, 72057594037928256, 72057594037928257, 72057594037928258, 72057594037928259, 72057594037928260, 72057594037928261, 72057594037928262, 72057594037928263, 72057594037928264, 72057594037928265, 72057594037928266, 72057594037928267, 72057594037928268, 72057594037928269, 72057594037928270, 72057594037928271, 72057594037928273, 72057594037928274, 72057594037928275, 72057594037928276, 72057594037928277, 72057594037928278, 72057594037928279, 72057594037928280, 72057594037928281, 72057594037928282, 72057594037928283, 72057594037928284, 72057594037928285, 72057594037928286, 72057594037928287, 72057594037928288, 72057594037928289, 72057594037928290, 72057594037928291, 72057594037928292, 72057594037928293, 72057594037928294, 72057594037928295, 72057594037928296, 72057594037928297, 72057594037928298, 72057594037928299, 72057594037928300, 72057594037928301, 72057594037928302, 72057594037928303, 72057594037928304, 72057594037928305, 72057594037928306, 72057594037928308, 72057594037928309, 72057594037928310, 72057594037928311, 72057594037928312, 72057594037928313, 72057594037928314, 72057594037928315, 72057594037928316, 72057594037928317, 72057594037928318, 72057594037928319, 72057594037928320, 72057594037928321, 72057594037928322, 72057594037928323, 72057594037928324, 72057594037928325, 72057594037928326, 72057594037928327, 72057594037928328, 72057594037928329, 72057594037928330, 72057594037928331, 72057594037928332, 72057594037928333, 72057594037928335, 72057594037928336, 72057594037928338, 72057594037928339, 72057594037928340, 72057594037928341, 360287970189639709, 360287970189639708, 360287970189640890, 360287970189640884, 360287970189640712, 360287970189640907, 360287970189640893, 360287970189639690, 360287970189640807, 360287970189640714, 360287970189640716, 360287970189640804, 360287970189640719, 360287970189640721, 360287970189640738, 360287970189640867, 360287970189640866, 360287970189640824, 360287970189640857, 360287970189640823, 360287970189640865, 360287970189640864, 360287970189640861, 360287970189640832, 360287970189640835, 360287970189640836, 360287970189640868, 360287970189640826, 360287970189640827, 360287970189640844, 360287970189640862, 360287970189640859, 360287970189640833, 360287970189640825, 360287970189640819, 360287970189640863, 360287970189640858, 360287970189640828, 360287970189640829, 360287970189640830, 360287970189640834, 360287970189640860, 360287970189640818, 360287970189640831, 360287970189640903, 360287970189640706, 360287970189640896, 360287970189640777, 360287970189640853, 360287970189639724])

In [20]:
locals_df[locals_df.FunctionStart==addr]

,FunctionStart,Signature,Name_Strip,Type_Strip,LocType_Strip,LocRegName_Strip,LocOffset_Strip,TypeCategory_Strip,TypeSeq_Strip,Name_Debug,Type_Debug,LocType_Debug,LocRegName_Debug,LocOffset_Debug,TypeCategory_Debug,TypeSeq_Debug,HasDWARF,TypeJson_Debug,BinaryId
373,1351728,"400,408,408,408",lVar1,int64,register,rcx,8,BUILTIN,int64,lVar3,int64,register,rcx,8.0,BUILTIN,int64,False,"{""kind"": ""BuiltinType"", ""name"": ""long"", ""is_fp...",0
374,1351728,"405,408,408,408",puVar2,uint64*,register,rdi,56,PTR,"PTR,uint64",ppVar4,player_t*,register,rdi,56.0,PTR,"PTR,STRUCT",False,"{""kind"": ""PointerType"", ""size"": 8, ""inner"": [{...",0
375,1351728,"4,408",bVar3,uchar,register,df,522,BUILTIN,uchar,bVar5,uchar,register,df,522.0,BUILTIN,uchar,False,"{""kind"": ""BuiltinType"", ""name"": ""byte"", ""is_fp...",0
376,1351728,"271,281",fVar4,float,register,xmm1_da,4640,BUILTIN,float,fVar6,float,register,xmm1_da,4640.0,BUILTIN,float,False,"{""kind"": ""BuiltinType"", ""name"": ""float"", ""is_f...",0
377,1351728,"0,144",uVar5,uint32,register,xmm1_db,4644,BUILTIN,uint32,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,NaN,0
378,1351728,"0,144,191,281",uVar6,uint32,register,xmm1_db,4644,BUILTIN,uint32,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,NaN,0
379,1351728,"505,548,865,908,1225,1268",local_378,uint64,stack,NaN,-888,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,NaN,0
380,1351728,"555,915,1275",local_370,uint64,stack,NaN,-880,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,NaN,0
381,1351728,"576,936,1296",local_368,uint64,stack,NaN,-872,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,NaN,0
382,1351728,"583,943,1303",local_360,uint64,stack,NaN,-864,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,NaN,0
383,1351728,"604,964,1324",local_358,uint64,stack,NaN,-856,BUILTIN,uint64,local_358,r_sheet*,stack,NaN,-856.0,PTR,"PTR,STRUCT",False,"{""kind"": ""PointerType"", ""size"": 8, ""inner"": [{...",0
384,1351728,"611,971,1331",local_350,uint64,stack,NaN,-848,BUILTIN,uint64,local_350,uint64,stack,NaN,-848.0,BUILTIN,uint64,False,"{""kind"": ""BuiltinType"", ""name"": ""undefined8"", ...",0
385,1351728,"632,992,1352",local_348,uint64,stack,NaN,-840,BUILTIN,uint64,local_348,uint64,stack,NaN,-840.0,BUILTIN,uint64,False,"{""kind"": ""BuiltinType"", ""name"": ""undefined8"", ...",0
386,1351728,"639,999,1359",local_340,uint64,stack,NaN,-832,BUILTIN,uint64,local_340,uint64,stack,NaN,-832.0,BUILTIN,uint64,False,"{""kind"": ""BuiltinType"", ""name"": ""undefined8"", ...",0
387,1351728,"660,1020,1380",local_338,uint64,stack,NaN,-824,BUILTIN,uint64,local_338,uint64,stack,NaN,-824.0,BUILTIN,uint64,False,"{""kind"": ""BuiltinType"", ""name"": ""undefined8"", ...",0
388,1351728,"667,1027,1387",local_330,uint64,stack,NaN,-816,BUILTIN,uint64,local_330,uint64,stack,NaN,-816.0,BUILTIN,uint64,False,"{""kind"": ""BuiltinType"", ""name"": ""undefined8"", ...",0
389,1351728,"688,1048,1408",local_328,uint64,stack,NaN,-808,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,NaN,0
390,1351728,"695,1055,1415",local_320,uint64,stack,NaN,-800,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,NaN,0
391,1351728,"828,1188,1548",local_318,uint64,stack,NaN,-792,BUILTIN,uint64,local_318,uint64,stack,NaN,-792.0,BUILTIN,uint64,False,"{""kind"": ""BuiltinType"", ""name"": ""undefined8"", ...",0
392,1351728,"723,1083,1443",local_310,uint64,stack,NaN,-784,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,NaN,0
393,1351728,"744,1104,1464",local_308,uint64,stack,NaN,-776,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,NaN,0
394,1351728,"751,1111,1471",local_300,uint64,stack,NaN,-768,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,NaN,0
395,1351728,"772,1132,1492",local_2f8,uint64,stack,NaN,-760,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,NaN,0
396,1351728,"779,1139,1499",local_2f0,uint64,stack,NaN,-752,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,NaN,0
397,1351728,"800,1160,1520",local_2e8,uint64,stack,NaN,-744,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,NaN,0
398,1351728,"807,1167,1527",local_2e0,uint64,stack,NaN,-736,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,NaN,0
399,1351728,"821,1181,1541",local_2d8,uint64,stack,NaN,-728,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,NaN,0
400,1351728,30,local_2c0,uint32,stack,NaN,-704,BUILTIN,uint32,width,int32,stack,NaN,-704.0,BUILTIN,int32,True,"{""kind"": ""BuiltinType"", ""name"": ""int"", ""is_fp""...",0
401,1351728,40,local_2bc,uint32,stack,NaN,-700,BUILTIN,uint32,height,int32,stack,NaN,-700.0,BUILTIN,int32,True,"{""kind"": ""BuiltinType"", ""name"": ""int"", ""is_fp""...",0
402,1351728,"1572,1601",local_2b8,uint64,stack,NaN,-696,BUILTIN,uint64,sword_swoosh,r_anim*,stack,NaN,-696.0,PTR,"PTR,STRUCT",True,"{""kind"": ""PointerType"", ""size"": 8, ""inner"": [{...",0
403,1351728,"58,121,179,477,519,879,1239",local_2b0,float,stack,NaN,-688,BUILTIN,float,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,NaN,0
404,1351728,"74,207,271",local_2ac,float,stack,NaN,-684,BUILTIN,float,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,NaN,0
405,1351728,"90,114",local_2a8,uint32,stack,NaN,-680,BUILTIN,uint32,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,NaN,0
406,1351728,106,local_2a4,uint32,stack,NaN,-676,BUILTIN,uint32,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,NaN,0
407,1351728,"179,258",local_2a0,float,stack,NaN,-672,BUILTIN,float,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,NaN,0
408,1351728,207,local_29c,float,stack,NaN,-668,BUILTIN,float,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,NaN,0
409,1351728,"227,251",local_298,uint32,stack,NaN,-664,BUILTIN,uint32,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,NaN,0
410,1351728,243,local_294,uint32,stack,NaN,-660,BUILTIN,uint32,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,NaN,0
411,1351728,304,local_290,uint32,stack,NaN,-656,BUILTIN,uint32,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,NaN,0
412,1351728,316,local_28c,uint32,stack,NaN,-652,BUILTIN,uint32,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,NaN,0
413,1351728,332,local_288,uint32,stack,NaN,-648,BUILTIN,uint32,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,NaN,0
414,1351728,348,local_284,uint32,stack,NaN,-644,BUILTIN,uint32,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,NaN,0
415,1351728,"364,512,872,1232",local_280,uint32,stack,NaN,-640,BUILTIN,uint32,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,NaN,0
416,1351728,380,local_27c,uint32,stack,NaN,-636,BUILTIN,uint32,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,NaN,0
417,1351728,"134,425",local_278,uint64,stack,NaN,-632,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,NaN,0
418,1351728,"144,432",local_270,uint64,stack,NaN,-624,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,NaN,0

In [21]:
funcs_df[funcs_df.FunctionStart==addr]

,FunctionStart,FunctionName_Debug,AstJson_Debug,FunctionName_Strip,AstJson_Strip,FunctionName_DWARF,BinaryId
36,1351728,init_game,/home/cls0027/exp_builds/astera.exp/rundata/ru...,FUN_0014a030,/home/cls0027/exp_builds/astera.exp/rundata/ru...,init_game,0

In [39]:
# ghidra imports
from ghidra.program.model.listing import Program

# my stuff (astlib)
from varlib import datatype, StructDatabase

###################################################################
# STUB CLASS/FUNCTIONS (aka what I need you to implement)
# -----------------------------------------------------------------
# This is a specific example of the general idea I'm looking for...lol
#
# What I mean is, we can totally tweak the API - this is just my best
# guess at a concrete example of what I need
###################################################################

class GhidraRetyper:
    def __init__(self, program:Program, reference_db:StructDatabase) -> None:
        # NOTE: I think this is all the Ghidra context you'll need
        # to access database things but add more if you need to
        self.program = program

        # right now the db I'm handing you has everything, but
        # the only guarantee is that it has definitions for all of
        # the structure/union types I actually ask you to apply
        # (and their dependencies) so it may be a subset of
        # Ghidra's full data type archive in general
        self.reference_db = reference_db

    def define_all_reference_types(self, overwrite_existing:bool=False):

        # this is where you may need to perform a topological sort
        # or w/e to handle dependencies (structs within structs)
        # Jacob did this recently...may be good to ask him about it
        print(f'DYLAN TODO: make sure this works for nested structure/union types...')

        # Caleb's naive implementation:
        for sid, stype in self.reference_db.structs_by_id:
            self.define_struct_type(stype, overwrite_existing)

        for uid, utype in self.reference_db.unions_by_id:
            self.define_union_type(utype, overwrite_existing)

    def define_struct_type(self, stype:datatype.StructType, overwrite_existing:bool=False):
        # define the structure using its given name and layout
        # --> IGNORE THE SID (stype.sid). Ghidra will assign its own ID and I will
        #     probably re-export the data type archive and remap the ids outside of this
        #     Regardless, I won't assume the sids are still valid once this completes.
        #     I will only assume the structure with the given name is defined in the database

        # also...if Ghidra wants you to pick a path for the data types (that show up in
        # the data type manager tree on the left), we can just use some hardcoded path
        # for all type we define for now (e.g. "/GhidraRetyper")

        # if overwrite_existing then blow away an existing struct with the same name
        print(f'DYLAN TODO: define structure type {stype.name} in Ghidra')

    def define_union_type(self, utype:datatype.UnionType, overwrite_existing:bool=False):
        # same as above, but unions...
        print(f'DYLAN TODO: define union type {utype.name} in Ghidra')

    def set_localvar_type(self, func_addr:int, local_name:str, dtype:datatype.DataType):
        print(f'DYLAN TODO: set decompiler local {local_name} in {func_addr:#x} to type {dtype}')

    def set_globalvar_type(self, global_name:int, global_type:datatype.DataType):
        # do this last: I don't have data for globals right now and we may not need them
        # ...but, while you're doing the others if this is straightforward you can add
        # support for globals too
        pass

    def set_param_type(self, func_addr:int, param_name:str, dtype:datatype.DataType):
        print(f'DYLAN TODO: set decompiler parameter {param_name} in {func_addr:#x} to type {dtype}')

    def set_return_type(self, func_addr:int, dtype:datatype.DataType):
        print(f'DYLAN TODO: set decompiler return type for function {func_addr:#x} to type {dtype}')

###################################################################
# DRIVER CODE
# -----------------------------------------------------------------
# My test cases and a good example of how I will use your class
###################################################################


# --------------------------------
# CALEB TODO:

# save/restore data types via TypeJson_Debug <<<

# --------------------------------
# STRUCT - include sid
# PTR - pointer, keep going...
# uint64, uchar, etc. - convert from standard name...

from varlib.datatype import datatype_from_dict
import json

retyper = GhidraRetyper(prog, sdb2)
func_locals = locals_df[locals_df.FunctionStart==addr]

for i in range(len(locals_df)):
    x = locals_df.iloc[i]
    if x.TypeCategory_Debug == 'COMP':
        continue
    # retyper.set_localvar_type(addr, x.Name_Strip, x.Type_Debug)
    try:
        print(i, x.TypeSeq_Debug, f'{datatype_from_dict(json.loads(x.TypeJson_Debug), sdb2)}')
    except KeyError:
        print(f'Failed on {i}, {x.TypeJson_Debug}')

0 ARR,uchar uchar[8]
1 int32 int32
2 int32 int32
3 int32 int32
7 int32 int32
8 int32 int32
9 float float
10 int32 int32
11 int32 int32
12 float float
13 int32 int32
14 int32 int32
16 PTR,STRUCT asset_t*
17 PTR,STRUCT asset_t*
18 PTR,STRUCT asset_t*
25 float float
26 int32 int32
27 int32 int32
28 double double
29 double double
31 float float
32 double double
33 uchar uchar
34 PTR,STRUCT r_particles*
35 int32 int32
37 float float
47 PTR,STRUCT r_sheet*
48 uint64 uint64
49 uint64 uint64
50 uint64 uint64
51 uint64 uint64
52 uint64 uint64
53 uint64 uint64
54 uint64 uint64
56 uint64 uint64
57 uint64 uint64
58 uint64 uint64
59 uint64 uint64
60 uint64 uint64
61 uint64 uint64
62 uint64 uint64
63 uint64 uint64
64 int32 int32
67 int32 int32
68 float float
70 int32 int32
72 float float
74 PTR,STRUCT r_anim*
84 int32 int32
86 float float
88 ARR,float float[2]
94 int64 int64
95 PTR,uint64 uint64*
96 uchar uchar
97 float float
98 float float
99 float float
100 float float
104 ARR,float float[2]
108 uint64 uint64
109 ARR,float float[2]
110 ARR,float float[2]
111 uint64 uint64
112 uint64 uint64
113 uint64 uint64
114 uint64 uint64
115 uint64 uint64
116 uint64 uint64
117 uint64 uint64
118 uint64 uint64
119 uint64 uint64
120 uint64 uint64
121 uint64 uint64
122 uint64 uint64
123 uint64 uint64
124 uint64 uint64
125 uint64 uint64
126 uint64 uint64
127 uint64 uint64
128 uint64 uint64
129 uint64 uint64
130 uint64 uint64
131 uint64 uint64
132 uint32 uint32
133 uint32 uint32
145 float float
146 float float
160 float float
162 uchar uchar
163 ushort ushort
164 int32 int32
165 int32 int32
166 float float
167 float float
168 float float
169 float float
170 int32 int32
171 PTR,PTR,char char**
172 PTR,STRUCT asset_t*
173 PTR,STRUCT GLFWvidmode*
192 ushort ushort
193 int32 int32
194 uchar uchar
195 PTR,STRUCT asset_t*
196 PTR,char char*
197 ushort ushort
199 uchar uchar
200 ushort ushort
209 double double
212 int32 int32
213 float float
214 PTR,STRUCT a_req*
215 PTR,int32 int32*
219 PTR,STRUCT c_aabb*
223 int32 int32
224 ARR,float float[2]
230 uint64 uint64
232 uint64 uint64
236 PTR,STRUCT r_camera*
238 uchar uchar
239 STRUCT r_particles
243 PTR,STRUCT r_sheet*
268 int32 int32
269 int32 int32
270 int32 int32
273 int32 int32
274 int32 int32
275 int32 int32
276 int32 int32
277 int32 int32
278 int32 int32
279 int32 int32
280 int32 int32
281 int32 int32
282 PTR,STRUCT asset_t*
283 PTR,STRUCT r_baked_quad*
284 PTR,STRUCT r_anim*
285 PTR,STRUCT r_anim*
286 PTR,STRUCT r_anim*
287 PTR,STRUCT r_anim*
288 PTR,STRUCT r_anim*
289 PTR,STRUCT r_anim*
290 PTR,STRUCT r_anim*
291 PTR,STRUCT r_anim*
292 PTR,STRUCT r_particles*
312 ARR,float float[4]
373 int64 int64
374 PTR,STRUCT player_t*
375 uchar uchar
376 float float
383 PTR,STRUCT r_sheet*
384 uint64 uint64
385 uint64 uint64
386 uint64 uint64
387 uint64 uint64
388 uint64 uint64
391 uint64 uint64
400 int32 int32
401 int32 int32
402 PTR,STRUCT r_anim*
419 int32 int32
420 int32 int32
421 int32 int32
422 int32 int32
423 double double
424 int32 int32
425 int32 int32
426 int32 int32
444 PTR,float float*
446 char char
448 ushort ushort
449 int32 int32
452 float float
453 char char
454 uchar uchar
455 ushort ushort
456 float float
457 double double
458 float float
459 int32 int32
460 int32 int32
461 float float
462 float float
463 PTR,STRUCT r_anim*
469 uchar uchar
470 int32 int32
474 float float
484 PTR,STRUCT r_anim*
485 PTR,STRUCT r_anim*
494 int32 int32
495 int32 int32
498 uchar uchar
499 PTR,STRUCT r_particles*
500 int32 int32
501 int32 int32
502 int32 int32
505 PTR,STRUCT asset_t*
506 PTR,char char*
507 char char
510 double double
514 STRUCT s_table
515 int32 int32
516 int32 int32
517 float float
518 STRUCT s_table
519 uchar uchar
520 int64 int64
521 int32 int32
525 uint64 uint64
526 uint64 uint64
527 uint64 uint64
543 PTR,STRUCT _IO_FILE*
544 PTR,STRUCT _IO_FILE*
545 PTR,uchar uchar*
546 uint64 uint64
547 uint64 uint64
548 PTR,STRUCT pak_write_t*
549 int32 int32
550 uint32 uint32
552 uint32 uint32
580 uchar uchar
581 PTR,STRUCT _IO_FILE*
582 PTR,STRUCT pak_wfile_t*
583 uint32 uint32
584 uint32 uint32
585 uint32 uint32
586 uint32 uint32
587 PTR,uchar uchar*
589 int32 int32
590 PTR,STRUCT _IO_FILE*
591 PTR,STRUCT pak_t*
592 PTR,STRUCT pak_file_t*
593 uint64 uint64
595 int32 int32
596 PTR,STRUCT pak_t*
597 PTR,uchar uchar*
599 PTR,STRUCT _IO_FILE*
600 uint64 uint64
601 uint32 uint32
603 PTR,STRUCT _IO_FILE*
604 uint64 uint64
605 uchar uchar
606 int32 int32
608 uint32 uint32
609 uint32 uint32
610 uint32 uint32
611 PTR,STRUCT pak_file_t*
612 uint32 uint32
613 PTR,uchar uchar*
618 PTR,STRUCT asset_t*
619 PTR,uchar uchar*
620 uint32 uint32
621 uint32 uint32
622 PTR,STRUCT asset_t*
623 PTR,STRUCT asset_t*
624 PTR,STRUCT _IO_FILE*
625 uint64 uint64
626 PTR,uchar uchar*
627 uint64 uint64
628 PTR,PTR,STRUCT asset_t**
629 PTR,STRUCT pak_t*
633 PTR,PTR,STRUCT asset_t**
634 PTR,STRUCT pak_t*
637 uint32 uint32
638 uint32 uint32
639 uint32 uint32
640 uint32 uint32
641 PTR,STRUCT asset_t*
642 PTR,STRUCT _IO_FILE*
643 uint64 uint64
644 PTR,uchar uchar*
645 uint64 uint64
646 PTR,STRUCT _IO_FILE*
647 uchar uchar
648 uint64 uint64
649 int32 int32
650 PTR,char char*
651 uint32 uint32
652 PTR,char char*
653 uint32 uint32
654 PTR,char char*
655 uint32 uint32
656 int32 int32
657 int32 int32
658 uint32 uint32
659 uint32 uint32
660 int32 int32
661 double double
664 uint32 uint32
666 int32 int32
667 int32 int32
668 int32 int32
669 int32 int32
670 int32 int32
671 uint32 uint32
672 ARR,uint32 uint32[32]
673 int32 int32
674 int32 int32
675 uint32 uint32
676 uint32 uint32
677 int32 int32
678 uchar uchar
679 PTR,uint32 uint32*
680 int32 int32
682 int32 int32
684 int32 int32
685 int32 int32
686 int32 int32
687 int32 int32
688 int32 int32
689 double double
690 int32 int32
691 double double
692 int32 int32
693 int32 int32
694 float float
695 double double
696 int32 int32
698 uint32 uint32
699 int32 int32
702 int32 int32
703 int32 int32
704 int32 int32
705 uint32 uint32
706 PTR,uchar uchar*
707 uint32 uint32
708 uchar uchar
709 uchar uchar
710 uchar uchar
711 uchar uchar
712 int32 int32
713 uint64 uint64
714 int64 int64
717 uint32 uint32
718 uchar uchar
719 int32 int32
722 uchar uchar
724 uint32 uint32
725 uint32 uint32
728 int32 int32
729 int32 int32
730 int32 int32
734 uchar uchar
737 uchar uchar
740 uchar uchar
741 int32 int32
743 int32 int32
744 int32 int32
745 int32 int32
746 int32 int32
747 int32 int32
749 uint32 uint32
750 uint32 uint32
751 int32 int32
752 uchar uchar
753 uint32 uint32
754 int32 int32
755 char char
757 int32 int32
758 int32 int32
759 uchar uchar
764 int32 int32
765 int32 int32
767 int32 int32
770 float float
771 int32 int32
772 int32 int32
773 float float
774 uchar uchar
777 int32 int32
778 int32 int32
779 int32 int32
781 int32 int32
782 float float
783 int32 int32
784 uint32 uint32
785 uint32 uint32
786 uint32 uint32
787 uint32 uint32
788 int32 int32
789 int32 int32
790 int32 int32
791 int32 int32
792 int32 int32
793 int32 int32
794 int32 int32
796 int32 int32
797 int32 int32
800 uint32 uint32
809 PTR,uchar uchar*
811 int64 int64
812 ARR,uchar uchar[8]
813 PTR,uchar uchar*
814 int32 int32
815 int32 int32
816 int32 int32
817 PTR,PTR,float float**
818 PTR,STRUCT stb_vorbis*
822 int32 int32
823 int32 int32
824 int32 int32
828 int32 int32
829 int32 int32
832 int32 int32
833 int32 int32
834 uint32 uint32
835 uint32 uint32
836 uint32 uint32
837 int32 int32
838 int32 int32
839 int32 int32
840 int32 int32
842 int32 int32
845 int32 int32
847 int32 int32
850 int32 int32
851 int32 int32
852 int32 int32
853 PTR,STRUCT Residue*
860 int64 int64
861 float float
862 float float
863 float float
864 float float
865 PTR,float float*
866 int32 int32
867 PTR,float float*
868 PTR,float float*
869 float float
870 float float
871 float float
872 float float
874 int32 int32
875 PTR,float float*
876 PTR,float float*
877 float float
878 float float
879 float float
880 float float
881 float float
882 float float
883 float float
884 float float
885 float float
886 float float
887 float float
888 float float
889 int32 int32
890 PTR,float float*
891 PTR,float float*
892 float float
893 float float
894 float float
895 float float
896 float float
897 float float
898 float float
899 float float
900 float float
901 PTR,float float*
902 PTR,float float*
903 float float
904 float float
905 int64 int64
906 char char
907 int32 int32
908 int32 int32
910 int32 int32
911 uint32 uint32
912 uint64 uint64
913 PTR,uchar uchar*
915 int64 int64
916 float float
917 float float
918 float float
919 float float
920 ARR,uchar uchar[8]
921 PTR,STRUCT stb_vorbis*
922 int32 int32
923 int32 int32
924 PTR,float float*
925 int32 int32
926 int32 int32
929 int32 int32
930 int32 int32
931 int32 int32
932 int32 int32
934 float float
935 float float
936 float float
937 float float
938 float float
939 float float
940 float float
941 float float
942 float float
943 float float
944 int32 int32
945 int32 int32
950 int32 int32
953 float float
954 float float
955 PTR,float float*
956 PTR,float float*
957 PTR,float float*
958 PTR,float float*
959 PTR,float float*
960 PTR,float float*
961 PTR,float float*
962 PTR,float float*
963 PTR,float float*
964 PTR,ushort ushort*
965 PTR,float float*
966 PTR,float float*
967 PTR,float float*
968 PTR,float float*
969 PTR,float float*
970 PTR,float float*
971 PTR,float float*
972 PTR,float float*
973 PTR,float float*
974 PTR,float float*
975 PTR,float float*
976 PTR,float float*
977 PTR,float float*
978 PTR,float float*
979 PTR,float float*
980 PTR,float float*
981 int64 int64
982 PTR,float float*
984 uint32 uint32
985 int32 int32
988 int32 int32
989 int32 int32
990 int32 int32
991 int32 int32
995 PTR,STRUCT Mode*
996 int32 int32
997 int32 int32
998 int32 int32
1000 uchar uchar
1001 uchar uchar
1002 short short
1004 PTR,short short*
1005 PTR,float float*
1007 int32 int32
1012 uint32 uint32
1013 int32 int32
1018 short short
1019 int32 int32
1020 int32 int32
1021 int32 int32
1022 int32 int32
1023 int32 int32
1024 int32 int32
1025 int32 int32
1027 int32 int32
1028 float float
1029 float float
1030 ARR,PTR,float float*[2]
1031 ARR,int32 int32[256]
1032 ARR,int32 int32[256]
1033 ARR,uchar uchar[256]
1036 int32 int32
1037 int32 int32
1038 int32 int32
1040 PTR,float float*
1042 int32 int32
1043 int32 int32
1044 int32 int32
1045 int32 int32
1046 int32 int32
1047 int32 int32
1048 int32 int32
1050 char char
1051 PTR,uchar uchar*
1053 uint32 uint32
1055 int32 int32
1056 PTR,uchar uchar*
1070 int32 int32
1071 int32 int32
1072 int32 int32
1073 int32 int32
1074 int32 int32
1075 int32 int32
1076 int32 int32
1077 int32 int32
1078 int32 int32
1079 int32 int32
1080 int32 int32
1081 float float
1082 uint32 uint32
1083 float float
1084 int32 int32
1085 int32 int32
1086 int32 int32
1087 int32 int32
1088 int32 int32
1089 int32 int32
1090 int32 int32
1091 uint32 uint32
1092 uint32 uint32
1093 uint32 uint32
1094 uint32 uint32
1095 uint32 uint32
1096 int32 int32
1097 int32 int32
1098 int32 int32
1099 int32 int32
1100 int32 int32
1101 uint32 uint32
1102 int32 int32
1103 int32 int32
1104 int32 int32
1105 int32 int32
1106 uint32 uint32
1107 int32 int32
1108 float float
1109 int32 int32
1110 int32 int32
1111 uint32 uint32
1112 int32 int32
1113 float float
1114 int32 int32
1115 PTR,uint32 uint32*
1116 PTR,uchar uchar*
1117 PTR,STRUCT Residue*
1118 PTR,STRUCT Mode*
1119 PTR,STRUCT Mapping*
1120 PTR,STRUCT Residue*
1121 PTR,STRUCT Floor1*
1122 PTR,STRUCT Floor0*
1123 PTR,STRUCT Codebook*
1124 PTR,ushort ushort*
1125 ARR,STRUCT stbv__floor_ordering[250]
1129 ARR,uchar uchar[64]
1132 int32 int32
1134 uint32 uint32
1137 uint32 uint32
1138 int32 int32
1139 int32 int32
1140 PTR,PTR,char char**
1141 STRUCT stb_vorbis_comment
1143 PTR,STRUCT stb_vorbis*
1150 int32 int32
1151 int32 int32
1152 uint32 uint32
1153 uint32 uint32
1154 int32 int32
1155 int32 int32
1157 int32 int32
1158 int32 int32
1159 int32 int32
1160 int32 int32
1163 PTR,STRUCT stb_vorbis*
1164 uchar uchar
1172 int64 int64
1174 uint32 uint32
1175 uint32 uint32
1179 uint32 uint32
1180 uint32 uint32
1182 uint32 uint32
1183 int32 int32
1184 uint32 uint32
1185 uint32 uint32
1186 uint32 uint32
1187 ARR,uchar uchar[27]
1188 uint32 uint32
1189 int32 int32
1190 int32 int32
1191 int32 int32
1199 ARR,uchar uchar[255]
1200 uint32 uint32
1201 uint32 uint32
1202 int32 int32
1203 uint32 uint32
1204 uint32 uint32
1208 int32 int32
1209 int32 int32
1210 int32 int32
1212 int32 int32
1213 double double
1214 double double
1225 int32 int32
1228 int32 int32
1229 int32 int32
1230 int32 int32
1231 int32 int32
1232 int32 int32
1233 uint32 uint32
1234 int32 int32
1237 int32 int32
1238 uint32 uint32
1239 uint32 uint32
1240 uint32 uint32
1241 uint32 uint32
1242 uint32 uint32
1243 uint32 uint32
1244 uint32 uint32
1245 uint32 uint32
1246 uint32 uint32
1247 uint32 uint32
1248 ARR,char char[6]
1249 uint32 uint32
1253 int32 int32
1254 int32 int32
1255 int32 int32
1257 int64 int64
1258 PTR,STRUCT stb_vorbis*
1259 uchar uchar
1264 uint64 uint64
1265 int64 int64
1266 PTR,STRUCT _IO_FILE*
1267 PTR,STRUCT stb_vorbis*
1269 PTR,STRUCT stb_vorbis*
1270 uchar uchar
1277 int32 int32
1278 int32 int32
1279 int32 int32
1280 int32 int32
1281 int32 int32
1282 int32 int32
1283 ARR,float float[32]
1284 uchar uchar
1285 int32 int32
1286 int32 int32
1287 int32 int32
1288 int32 int32
1289 int32 int32
1290 ARR,float float[32]
1291 int32 int32
1292 int32 int32
1294 PTR,PTR,float float**
1295 int32 int32
1297 PTR,short short*
1300 int32 int32
1302 PTR,short short*
1303 int32 int32
1304 int32 int32
1305 PTR,STRUCT stb_vorbis*
1307 PTR,PTR,float float**
1308 int32 int32
1309 PTR,short short*
1311 int32 int32
1312 PTR,PTR,float float**
1313 int32 int32
1315 int32 int32
1316 PTR,PTR,float float**
1317 PTR,short short*
1318 int32 int32
1319 int32 int32
1320 int32 int32
1321 int32 int32
1322 int32 int32
1323 int32 int32
1324 int32 int32
1325 PTR,short short*
1326 PTR,STRUCT stb_vorbis*
1327 PTR,short short*
1328 PTR,short short*
1329 int32 int32
1330 int32 int32
1331 int32 int32
1332 int32 int32
1333 int32 int32
1334 int32 int32
1335 int32 int32
1336 PTR,short short*
1337 PTR,STRUCT stb_vorbis*
1338 PTR,short short*
1339 int32 int32
1340 PTR,float float*
1342 int32 int32
1343 int32 int32
1344 int32 int32
1345 int32 int32
1346 PTR,PTR,float float**
1347 int32 int32
1349 int32 int32
1350 int32 int32
1351 int32 int32
1352 PTR,PTR,float float**
1353 PTR,STRUCT _IO_FILE*
1354 PTR,uchar uchar*
1355 uint64 uint64
1356 uint64 uint64
1357 PTR,STRUCT a_layer*
1358 ushort ushort
1359 ushort ushort
1360 char char
1361 ushort ushort
1362 ushort ushort
1363 PTR,STRUCT a_layer*
1364 ushort ushort
1365 uint32 uint32
1366 uint32 uint32
1367 uchar uchar
1368 uchar uchar
1369 ushort ushort
1370 uint32 uint32
1371 uint32 uint32
1372 float float
1373 uint32 uint32
1374 uint32 uint32
1375 int32 int32
1376 STRUCT stb_vorbis_info
1377 char char
1378 uint64 uint64
1379 PTR,char char*
1380 char char
1382 PTR,STRUCT a_ctx*
1392 ushort ushort
1393 ushort ushort
1394 ushort ushort
1395 ushort ushort
1396 ushort ushort
1397 ushort ushort
1398 int32 int32
1400 PTR,STRUCT ALCdevice_struct*
1401 PTR,STRUCT ALCcontext_struct*
1404 uchar uchar
1405 PTR,STRUCT a_song*
1407 ushort ushort
1409 ushort ushort
1410 ushort ushort
1412 ushort ushort
1413 uchar uchar
1414 uchar uchar
1415 ushort ushort
1416 int32 int32
1417 int32 int32
1418 float float
1419 uint32 uint32
1420 uint32 uint32
1421 uint32 uint32
1422 float float
1423 uint32 uint32
1424 uint32 uint32
1425 int32 int32
1426 uint32 uint32
1427 STRUCT stb_vorbis_info
1428 char char
1429 ushort ushort
1430 ushort ushort
1431 ushort ushort
1432 int32 int32
1433 int32 int32
1434 float float
1435 PTR,STRUCT a_sfx*
1436 PTR,STRUCT a_song*
1438 PTR,STRUCT a_layer*
1439 uchar uchar
1440 ushort ushort
1441 ushort ushort
1442 ushort ushort
1443 uint32 uint32
1444 uint32 uint32
1445 float float
1446 PTR,STRUCT a_sfx*
1447 PTR,STRUCT a_layer*
1448 PTR,STRUCT a_buf*
1449 PTR,STRUCT a_sfx*
1450 PTR,STRUCT a_sfx*
1451 ushort ushort
1455 ushort ushort
1457 PTR,STRUCT stb_vorbis*
1458 PTR,uint32 uint32*
1459 float float
1463 uchar uchar
1464 ushort ushort
1465 PTR,STRUCT a_ctx*
1466 uchar uchar
1467 char char
1468 ushort ushort
1469 ushort ushort
1470 int32 int32
1471 uint32 uint32
1472 uint32 uint32
1473 uint32 uint32
1474 uint32 uint32
1475 int32 int32
1476 PTR,STRUCT a_song*
1477 ushort ushort
1478 uint32 uint32
1479 PTR,uchar uchar*
1480 uchar uchar
1481 PTR,STRUCT a_song*
1482 ushort ushort
1483 PTR,STRUCT a_song*
1488 ushort ushort
1489 ushort ushort
1493 double double
1494 uint32 uint32
1495 double double
1496 uchar uchar
1499 uchar uchar
1500 int32 int32
1501 uint32 uint32
1502 int32 int32
1503 ushort ushort
1504 ushort ushort
1505 short short
1506 int32 int32
1507 ushort ushort
1508 int32 int32
1509 int32 int32
1510 int32 int32
1511 int32 int32
1512 int32 int32
1513 int32 int32
1514 int32 int32
1515 int32 int32
1516 int32 int32
1517 PTR,ushort ushort*
1518 PTR,STRUCT a_buf*
1519 PTR,STRUCT stb_vorbis*
1520 ushort ushort
1521 uint32 uint32
1522 PTR,uchar uchar*
1525 int32 int32
1526 ushort ushort
1527 PTR,STRUCT a_buf*
1530 uchar uchar
1531 uchar uchar
1540 ushort ushort
1541 ushort ushort
1542 PTR,STRUCT a_fx*
1543 uchar uchar
1544 PTR,STRUCT a_fx*
1545 ENUM a_fx_type
1546 PTR,float float*
1547 uchar uchar
1549 ENUM a_fx_type
1550 PTR,STRUCT a_fx*
1563 float float
1564 float float
1565 float float
1567 float float
1568 float float
1569 float float
1570 float float
1571 float float
1572 float float
1573 float float
1574 float float
1575 float float
1576 float float
1577 float float
1578 ushort ushort
1579 float float
1580 ushort ushort
1581 PTR,STRUCT a_filter*
1582 ENUM a_filter_type
1583 uchar uchar
1585 uchar uchar
1586 PTR,STRUCT a_filter*
1587 ushort ushort
1588 PTR,uint32 uint32*
1589 ushort ushort
1590 PTR,STRUCT a_layer*
1591 int32 int32
1592 ushort ushort
1593 PTR,STRUCT a_layer*
1594 PTR,STRUCT a_layer*
1595 uchar uchar
1596 PTR,STRUCT a_layer*
1597 uchar uchar
1598 PTR,STRUCT a_layer*
1599 uchar uchar
1600 PTR,STRUCT a_layer*
1601 uchar uchar
1602 PTR,STRUCT a_layer*
1603 uchar uchar
1604 PTR,STRUCT a_layer*
1605 float float
1606 float float
1607 float float
1608 STRUCT a_timeline
1609 PTR,void void*
1610 PTR,float float*
1611 uint32 uint32
1613 PTR,STRUCT a_keyframe*
1614 PTR,STRUCT a_keyframe*
1615 float float
1616 float float
1617 uint32 uint32
1622 uint32 uint32
1624 uint32 uint32
1627 int32 int32
1628 int32 int32
1629 int32 int32
1632 int32 int32
1634 float float
1635 int32 int32
1636 float float
1637 int32 int32
1640 int32 int32
1641 int32 int32
1662 uchar uchar
1668 float float
1671 ARR,float float[2]
1672 ARR,float float[2]
1673 uchar uchar
1674 float float
1675 float float
1676 float float
1677 float float
1678 float float
1679 double double
1680 double double
1688 float float
1689 float float
1690 float float
1691 float float
1692 float float
1693 double double
1694 double double
1712 float float
1715 ARR,float float[2]
1716 ARR,float float[2]
1717 ARR,float float[2]
1718 ARR,float float[2]
1743 float float
1747 float float
1755 float float
1756 float float
1757 float float
1758 ARR,float float[2]
1759 ARR,float float[2]
1770 ARR,float float[2]
1786 ARR,float float[2]
1787 ARR,float float[2]
1788 ARR,float float[2]
1793 ARR,float float[2]
1803 float float
1805 ARR,float float[2]
1806 ARR,float float[2]
1821 ARR,float float[2]
1822 ARR,float float[2]
1823 ARR,float float[2]
1828 ARR,float float[2]
1838 PTR,STRUCT c_shape*
1846 int64 int64
1847 PTR,STRUCT tm*
1848 uchar uchar
1849 PTR,STRUCT _IO_FILE*
1850 PTR,STRUCT _IO_FILE*
1851 uint64 uint64
1852 int64 int64
1853 uchar uchar
1854 char char
1855 PTR,char char*
1856 PTR,STRUCT _IO_FILE*
1860 char char
1861 PTR,STRUCT _IO_FILE*
1865 ushort ushort
1866 PTR,int32 int32*
1871 double double
1872 double double
1873 double double
1879 ushort ushort
1881 int32 int32
1882 int32 int32
1887 char char
1888 uchar uchar
1889 uchar uchar
1890 uchar uchar
1891 uchar uchar
1892 int32 int32
1893 PTR,STRUCT i_joy*

In [23]:
x = locals_df.iloc[6584]

# dtmgr.findDataTypeForID(ghidra.util.UniversalID(360287970189640893))
# type(dtmgr.findDataType('_XRRScreenResources'))
funcs_df[funcs_df.FunctionStart==1952083]
x

FunctionStart                                                   1952083
Signature                                                   114,169,267
Name_Strip                                                        uVar1
Type_Strip                                                       uint64
LocType_Strip                                                  register
LocRegName_Strip                                                    rax
LocOffset_Strip                                                       0
TypeCategory_Strip                                              BUILTIN
TypeSeq_Strip                                                    uint64
Name_Debug                                                       pXVar1
Type_Debug                                          XRRScreenResources*
LocType_Debug                                                  register
LocRegName_Debug                                                    rax
LocOffset_Debug                                                     0.0
TypeCategory_Debug                                                  PTR
TypeSeq_Debug                                                PTR,STRUCT
HasDWARF                                                          False
TypeJson_Debug        {"kind": "PointerType", "size": 8, "inner": [{...
BinaryId                                                              0
Name: 6584, dtype: object

In [24]:
td = list(dtmgr.getAllDataTypes())[0]

In [37]:
# OK, currently the AST will contain typedef type ids and names for typedef'd structs
# and unions, but defines them as the canonical struct/union definition
# --> if we simply double-map the ids/names, everything should work fine...

isinstance(td, ghidra.program.model.data.TypeDef)

typedef_types = [x for x in dtmgr.getAllDataTypes() if isinstance(x, ghidra.program.model.data.TypeDef)]
print(len(typedef_types))
print(len([td for td in typedef_types if isinstance(td.getBaseDataType(), ghidra.program.model.data.Structure)]))
utype = [td for td in typedef_types if isinstance(td.getBaseDataType(), ghidra.program.model.data.Union)][0].getBaseDataType()
td = [td for td in typedef_types if isinstance(td.getBaseDataType(), ghidra.program.model.data.Union)][0]
utype

1231
50

/DWARF/Xlib.h/_XEvent
pack()
Union _XEvent {
   0   int   4   type   ""
   0   XAnyEvent   40   xany   ""
   0   XKeyEvent   96   xkey   ""
   0   XButtonEvent   96   xbutton   ""
   0   XMotionEvent   96   xmotion   ""
   0   XCrossingEvent   104   xcrossing   ""
   0   XFocusChangeEvent   48   xfocus   ""
   0   XExposeEvent   64   xexpose   ""
   0   XGraphicsExposeEvent   72   xgraphicsexpose   ""
   0   XNoExposeEvent   48   xnoexpose   ""
   0   XVisibilityEvent   48   xvisibility   ""
   0   XCreateWindowEvent   72   xcreatewindow   ""
   0   XDestroyWindowEvent   48   xdestroywindow   ""
   0   XUnmapEvent   56   xunmap   ""
   0   XMapEvent   56   xmap   ""
   0   XMapRequestEvent   48   xmaprequest   ""
   0   XReparentEvent   72   xreparent   ""
   0   XConfigureEvent   88   xconfigure   ""
   0   XGravityEvent   56   xgravity   ""
   0   XResizeRequestEvent   48   xresizerequest   ""
   0   XConfigureRequestEvent   96   xconfigurerequest   ""
   0   XCirculateEvent   56   xcirculate   ""
   0   XCirculateRequestEvent   56   xcirculaterequest   ""
   0   XPropertyEvent   64   xproperty   ""
   0   XSelectionClearEvent   56   xselectionclear   ""
   0   XSelectionRequestEvent   80   xselectionrequest   ""
   0   XSelectionEvent   72   xselection   ""
   0   XColormapEvent   56   xcolormap   ""
   0   XClientMessageEvent   96   xclient   ""
   0   XMappingEvent   56   xmapping   ""
   0   XErrorEvent   40   xerror   ""
   0   XKeymapEvent   72   xkeymap   ""
   0   XGenericEvent   40   xgeneric   ""
   0   XGenericEventCookie   56   xcookie   ""
   0   long[24]   192   pad   ""
}
Size = 192   Actual Alignment = 8

In [38]:
sdb2.unions_by_id[td.key]

union _XEvent {
	[int32 type, XAnyEvent xany, XKeyEvent xkey, XButtonEvent xbutton, XMotionEvent xmotion, XCrossingEvent xcrossing, XFocusChangeEvent xfocus, XExposeEvent xexpose, XGraphicsExposeEvent xgraphicsexpose, XNoExposeEvent xnoexpose, XVisibilityEvent xvisibility, XCreateWindowEvent xcreatewindow, XDestroyWindowEvent xdestroywindow, XUnmapEvent xunmap, XMapEvent xmap, XMapRequestEvent xmaprequest, XReparentEvent xreparent, XConfigureEvent xconfigure, XGravityEvent xgravity, XResizeRequestEvent xresizerequest, XConfigureRequestEvent xconfigurerequest, XCirculateEvent xcirculate, XCirculateRequestEvent xcirculaterequest, XPropertyEvent xproperty, XSelectionClearEvent xselectionclear, XSelectionRequestEvent xselectionrequest, XSelectionEvent xselection, XColormapEvent xcolormap, XClientMessageEvent xclient, XMappingEvent xmapping, XErrorEvent xerror, XKeymapEvent xkeymap, XGenericEvent xgeneric, XGenericEventCookie xcookie, int64[24] pad]
}

In [26]:
sdb2.unions_by_id[utype.key]

union _XEvent {
	[int32 type, XAnyEvent xany, XKeyEvent xkey, XButtonEvent xbutton, XMotionEvent xmotion, XCrossingEvent xcrossing, XFocusChangeEvent xfocus, XExposeEvent xexpose, XGraphicsExposeEvent xgraphicsexpose, XNoExposeEvent xnoexpose, XVisibilityEvent xvisibility, XCreateWindowEvent xcreatewindow, XDestroyWindowEvent xdestroywindow, XUnmapEvent xunmap, XMapEvent xmap, XMapRequestEvent xmaprequest, XReparentEvent xreparent, XConfigureEvent xconfigure, XGravityEvent xgravity, XResizeRequestEvent xresizerequest, XConfigureRequestEvent xconfigurerequest, XCirculateEvent xcirculate, XCirculateRequestEvent xcirculaterequest, XPropertyEvent xproperty, XSelectionClearEvent xselectionclear, XSelectionRequestEvent xselectionrequest, XSelectionEvent xselection, XColormapEvent xcolormap, XClientMessageEvent xclient, XMappingEvent xmapping, XErrorEvent xerror, XKeymapEvent xkeymap, XGenericEvent xgeneric, XGenericEventCookie xcookie, int64[24] pad]
}

In [27]:
ss = sdb2.sids_by_name['_XRRScreenResources'][0]
print(sdb2.structs_by_id[ss].ghidra_uid)
print(360287970189640721)

3579440783260282748
360287970189640721

In [28]:
from ghidralib.decompiler import get_decompiler_interface

ifc = get_decompiler_interface(prog)

In [29]:
ff = [x for x  in prog.functionManager.getFunctions(True) if x.getEntryPoint().offset==addr][0]
print(ff.name)
res = ifc.decompileFunction(ff, 240, None)

init_game

In [30]:
# this works!
xx = res.getHighFunction().getDataTypeManager().findBaseType('player_t', 72057594037927994)
(xx.getUniversalID(), xx.getKey())

(3579440781830025081, 72057594037927994)

In [31]:
xx.getUniversalID().getValue()
hex(72057594037927949)

'0x10000000000000d'

In [32]:
# can I just create a 1-time map of all struct types (using an arbitrary decompiled func?)
k = list(sdb2.structs_by_id.keys())[1]

sdef = sdb2.structs_by_id[k]
k, sdef.name

res.getHighFunction().getDataTypeManager().findBaseType(sdef.name, k)

/ELF/Elf64_Phdr
pack(disabled)
Structure Elf64_Phdr {
   0   Elf_ProgramHeaderType   4   p_type   ""
   4   dword   4   p_flags   ""
   8   qword   8   p_offset   ""
   16   qword   8   p_vaddr   ""
   24   qword   8   p_paddr   ""
   32   qword   8   p_filesz   ""
   40   qword   8   p_memsz   ""
   48   qword   8   p_align   ""
}
Size = 56   Actual Alignment = 1

In [33]:
import fixedint

dsid = 72057594037927994
sname = 'player_t'
# gsid = 3579440781830025081

# can I generate dsid from Ghidra name?

res = fixedint.UInt64(123)

# res = 123
for c in sname:
    res = fixedint.UInt64((res<<8) | (res>>56))
    res += fixedint.UInt64(ord(c))
    if (res&1) == 0:
        res ^= fixedint.UInt64(0xfeabfeab)
tmp = fixedint.UInt64(1)
tmp <<= 63
res |= tmp

print(res)
res == dsid
hex(dsid)
dsid==xx.getKey()

11945691551399600393

True

In [34]:
sdef.layout.fields_by_offset[0x30].size+0x30

sizehash = fixedint.UInt64(56)
sizehash *= fixedint.UInt64(0x98251033aecbabaf)
res ^= sizehash
res
# res ^ sizehash


# sizehash = fixedint.UInt64(56)
# sizehash ^ fixedint.UInt64(0x98251033aecbabaf)

UInt64(17139596697048149825)

In [35]:
tmp = fixedint.UInt64(1)
tmp <<= 63
hex(tmp)
type(tmp)
type(tmp<<8)

fixedint.aliases.UInt64

In [36]:
#!pip install fixedint